# Generated by Django 5.2 on 2025-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uet_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uet',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
