# Generated by Django 5.2 on 2025-11-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_delete_uet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
