# Generated by Django 5.2 on 2025-12-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_full_name_users_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('cgpa', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
