# Generated by Django 5.2 on 2025-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_students_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(),
        ),
    ]
