# Generated by Django 5.2 on 2025-12-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_students_cgpa_alter_students_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
