# Generated by Django 5.2 on 2025-12-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_emails_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('phone', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='emails',
        ),
    ]
