# Generated by Django 5.2 on 2025-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_admin_person_delete_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_person',
            name='phone',
            field=models.CharField(),
        ),
    ]
