# Generated by Django 5.2 on 2025-12-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_admin_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='subusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('phone', models.CharField()),
                ('mode', models.CharField()),
            ],
        ),
    ]
