# Generated by Django 5.2 on 2025-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_person',
            name='group',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='admin_person',
            name='mode',
            field=models.CharField(null=True),
        ),
    ]
