# Generated by Django 5.2 on 2025-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_admin_person_group_admin_person_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_person',
            name='group',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='admin_person',
            name='mode',
            field=models.CharField(),
        ),
    ]
