# Generated by Django 5.2 on 2025-12-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_admin_person_group_alter_admin_person_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('fullname', models.CharField()),
                ('displayname', models.CharField()),
                ('residence', models.CharField()),
                ('source', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='admin_person',
        ),
        migrations.DeleteModel(
            name='subusers',
        ),
    ]
