# Generated by Django 5.2 on 2025-12-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_users_delete_admin_person_delete_subusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.CharField(null=True),
        ),
    ]
