# Generated by Django 5.2 on 2025-12-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_users_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='group',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='users',
            name='source',
        ),
    ]
