# Generated by Django 5.2 on 2025-12-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_users_displayname_remove_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='displayname',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='fullname',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='residence',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='source',
            field=models.CharField(null=True),
        ),
    ]
