# Generated by Django 5.2 on 2025-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_users_displayname_users_email_users_fullname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='appusers',
        ),
    ]
