# Generated by Django 5.2 on 2025-12-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_users_appusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(null=True)),
                ('password', models.CharField(null=True)),
                ('fullname', models.CharField(null=True)),
                ('displayname', models.CharField(null=True)),
                ('residence', models.CharField(null=True)),
                ('source', models.CharField(null=True)),
                ('group', models.CharField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='appusers',
        ),
    ]
