# Generated by Django 5.2 on 2025-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_app_users_delete_appusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_users',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
