# Generated by Django 5.2 on 2025-12-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_app_users_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_users',
            name='isactive',
        ),
    ]
