# Generated by Django 5.2 on 2025-12-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_app_users_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_users',
            old_name='group',
            new_name='parent',
        ),
    ]
