# Generated by Django 5.2 on 2025-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_group_app_users_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_users',
            name='account',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='app_users',
            name='subscription',
            field=models.CharField(null=True),
        ),
    ]
