# Generated by Django 5.2 on 2025-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_app_users_account_app_users_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_users',
            name='last_login',
            field=models.CharField(null=True),
        ),
    ]
