# Generated by Django 5.2 on 2025-12-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_app_users_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='techfest_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('fullname', models.CharField()),
                ('otp', models.CharField()),
                ('token', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='app_users',
        ),
    ]
