# Generated by Django 5.2 on 2025-12-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_techfest_participants_delete_app_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='techfest_participants',
            name='events',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='techfest_participants',
            name='otp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='techfest_participants',
            name='token',
            field=models.CharField(null=True),
        ),
    ]
