# Generated by Django 5.2 on 2025-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_techfest_participants_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfest_participants',
            name='otp',
            field=models.CharField(),
        ),
    ]
