# Generated by Django 6.0 on 2026-01-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_techfest_participants_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='techfest_participants',
        ),
    ]
