# Generated by Django 6.0 on 2026-01-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0029_delete_techfest_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='techfest_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
                ('fullname', models.CharField()),
                ('otp', models.CharField()),
                ('token', models.CharField(null=True)),
                ('events', models.JSONField(default=list)),
            ],
        ),
    ]
